[package]
name = "rust-tutorials"
version = "0.1.0"
authors = ["Michael Micucci <michael.micucci@exchange.co.jp>"]
edition = "2018"

[dependencies]
chrono = "*"
futures = "0.3"
tokio = { version = "1.0", features = ["full"] }
